name: Trigger Cleanup on PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - '*'

jobs:
  trigger-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PR_TOKEN }}
          repository: sergii-nosachenko/github-prs-reviews-collector
          event-type: pr-cleanup
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}"}'
